// Generates src/devicon-slim.css from the installed devicon package: the
// @font-face ships only the woff font (browsers never fetch eot/ttf/svg, but
// bundling them adds ~9MB to the embedded binary), and only the icon classes
// referenced by src/utils/fileIcons.ts are kept. Re-run after bumping devicon:
//   node scripts/devicon-slim.mjs
import { readFileSync, writeFileSync } from "node:fs";

const iconsSource = readFileSync(
	new URL("../src/utils/fileIcons.ts", import.meta.url),
	"utf8",
);
const wanted = new Set(iconsSource.match(/devicon-[a-z0-9-]+/g));
if (wanted.size === 0) {
	throw new Error("no devicon classes found in fileIcons.ts");
}

const css = readFileSync(
	new URL("../node_modules/devicon/devicon.min.css", import.meta.url),
	"utf8",
);

const usesWantedClass = (selector) =>
	selector
		.split(",")
		.some((s) => wanted.has(s.trim().match(/^\.([a-z0-9-]+)/)?.[1] ?? ""));

const rules = [];
for (const rule of css.match(/[^{}]+\{[^{}]*\}/g) ?? []) {
	const selector = rule.slice(0, rule.indexOf("{"));
	if (!selector.startsWith("@") && usesWantedClass(selector)) {
		rules.push(rule.trim());
	}
}
if (rules.length < wanted.size) {
	throw new Error(
		`only ${rules.length} rules found for ${wanted.size} classes`,
	);
}

const header = `/* Generated by scripts/devicon-slim.mjs — do not edit. Re-run after changing
 * src/utils/fileIcons.ts or bumping the devicon package. */`;

const fontFace = `@font-face{font-family:"devicon";src:url("../node_modules/devicon/fonts/devicon.woff") format("woff");font-weight:normal;font-style:normal;font-display:block}`;

const base = `[class^=devicon-],[class*=" devicon-"]{font-family:"devicon" !important;speak:never;font-style:normal;font-weight:normal;font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}`;

writeFileSync(
	new URL("../src/devicon-slim.css", import.meta.url),
	[header, fontFace, base, ...rules, ""].join("\n"),
);

console.log(
	`devicon-slim.css: ${rules.length} rules for ${wanted.size} classes`,
);
